image: python:3.8

services:
  - postgres:latest

variables:
  POSTGRES_DB: mydatabase
  POSTGRES_USER: myuser
  POSTGRES_PASSWORD: mypassword
  DATABASE_URL: postgres://myuser:mypassword@postgres:5432/mydatabase
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - build
  - test
  - deploy

before_script:
  - git submodule update --init --recursive
  - pip install -r requirements.txt
  - python manage.py migrate  # Menerapkan migrasi basis data

build:
  stage: build
  script:
    - echo "Membangun proyek..."
    # Tambahkan perintah build Anda di sini

test:
  stage: test
  script:
    - echo "Menjalankan tes..."
    - python manage.py test  # Menjalankan tes

deploy:
  stage: deploy
  script:
    - echo "Menyebarkan aplikasi..."
    # Tambahkan perintah untuk deployment di sini

