stages:
  - build
  - test
  - deploy

variables:
  VENV_DIR: venv

build:
  stage: build
  image: python:3.8
  script:
    - echo "Creating virtual environment..."
    - python -m venv $VENV_DIR
    - source $VENV_DIR/bin/activate
    - echo "Installing dependencies..."
    - pip install -r requirements.txt
  artifacts:
    paths:
      - $VENV_DIR/

test:
  stage: test
  image: python:3.8
  dependencies:
    - build
  script:
    - echo "Running tests..."
    - source $VENV_DIR/bin/activate
    - python -m unittest discover -s trackingga/tests

deploy:
  stage: deploy
  image: python:3.8
  dependencies:
    - build
  script:
    - echo "Deploying the application..."
    - source $VENV_DIR/bin/activate
    - python manage.py migrate
  only:
    - main
