stages:
  - build
  - test
  - deploy

build:
  stage: build
  image: python:3.8
  services:
    - postgres:latest
  variables:
    POSTGRES_DB: mydatabase
    POSTGRES_USER: user
    POSTGRES_PASSWORD: password
  script:
    - echo "Building the application..."
    - python -m venv venv  # Membuat virtual environment
    - source venv/bin/activate  # Mengaktifkan virtual environment
    - pip install -r requirements.txt

test:
  stage: test
  image: python:3.8
  script:
    - echo "Running tests..."
    - source venv/bin/activate  # Mengaktifkan virtual environment
    - python conf.py test  # Menjalankan pengujian Django

deploy:
  stage: deploy
  image: python:3.8
  script:
    - echo "Deploying the application..."
    - source venv/bin/activate  # Mengaktifkan virtual environment
    - python conf.py migrate  # Menjalankan migrasi
  only:
    - main
