stages:
  - build
  - test
  - deploy

variables:
  APP_ENV: testing
  DB_CONNECTION: sqlite
  DB_DATABASE: ":memory:"
  CACHE_DRIVER: file
  SESSION_DRIVER: file
  QUEUE_DRIVER: sync

cache:
  paths:
    - vendor/
    - node_modules/

before_script:
  - apt-get update -y
  - apt-get install -y git unzip libzip-dev
  - pwd  # Menampilkan direktori kerja saat ini
  - ls -la  # Menampilkan semua file dan direktori
  - cp .env.example .env
  - composer install --prefer-dist --no-ansi --no-interaction --no-progress --no-scripts
  - php artisan key:generate
  - php artisan config:cache

build:
  stage: build
  script:
    - npm install
    - npm run production
  artifacts:
    paths:
      - public/js
      - public/css

test:
  stage: test
  script:
    - vendor/bin/phpunit --coverage-text --colors=never

deploy:
  stage: deploy
  script:
    - echo "Deploying the application..."
    # Tambahkan perintah untuk menyebarkan aplikasi Anda di sini
  only:
    - main